### ISSUE TITLE
Noisy is failing on websites with redirection errors

### ISSUE THREAD

**Issue by Arduous** [1tayH/noisy#11]
https://www.fossil.com/us/en/account-dashboard/registered-products.html is _currently_ not working, with browsers (Chromium, Firefox) returning "ERR_INVALID_REDIRECT".

Noisy  crashes when visiting it 

        pi@RaspSalon:~/dev/noisy $ python3 noisy.py --config config.json --log debug
        INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.fossil.com
        DEBUG:urllib3.connectionpool:"GET /us/en/account-dashboard/registered-products.html HTTP/1.1" 302 20
        Traceback (most recent call last):
          File "noisy.py", line 274, in <module>
            main()
          File "noisy.py", line 270, in main
            crawler.crawl()
          File "noisy.py", line 238, in crawl
            body = self._request(url).content
          File "noisy.py", line 49, in _request
            response = requests.get(url, headers=headers, timeout=5)
          File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
            return request('get', url, **kwargs)
          File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
            return session.request(method=method, url=url, **kwargs)
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
            resp = self.send(prep, **send_kwargs)
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 595, in send
            history = [resp for resp in gen] if allow_redirects else []
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 595, in <listcomp>
            history = [resp for resp in gen] if allow_redirects else []
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 189, in resolve_redirects
            allow_redirects=False,
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
            r = adapter.send(request, **kwargs)
          File "/usr/lib/python3/dist-packages/requests/adapters.py", line 329, in send
            conn = self.get_connection(request.url, proxies)
          File "/usr/lib/python3/dist-packages/requests/adapters.py", line 243, in get_connection
            conn = self.poolmanager.connection_from_url(url)
          File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 130, in connection_from_url
            u = parse_url(url)
          File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 143, in parse_url
            raise LocationParseError(url)
        urllib3.exceptions.LocationParseError: Failed to parse: www.fossil.com:-1

My view is that requests should not let through an uncaught error from urllib3. I will try to raise the issue to them, but will provide a temporary workaround for noisy.

**Comment by 1tayH** [comment]
Hi, thanks for the issue 😄 
Just for reference, the problem was that the location header returned by the server was a URL with an invalid port:
```
HTTP/2 302 
server: Apache
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
location: https://www.fossil.com:-1/content/fossil/us/en/sign-in.html
access-control-allow-origin: https://www.fossil.com
access-control-allow-credentials: true
content-type: text/html;charset=UTF-8
expires: Sun, 22 Jul 2018 18:13:58 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Sun, 22 Jul 2018 18:13:58 GMT
set-cookie: renderid=rend04; path=/;
```
