### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by prykon** [1tayH/noisy#42]
```Traceback (most recent call last):
  File "/opt/noisy/noisy.py", line 262, in <module>
    main()
  File "/opt/noisy/noisy.py", line 253, in main
    crawler.load_config_file(args.config)
  File "/opt/noisy/noisy.py", line 177, in load_config_file
    config = json.load(config_file)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 15 column 5 (char 360)```

The only thing I did was delete one or two URLs from the `config.json` file. Here is the relevant content:

```{
    "max_depth": 25,
    "min_sleep": 3,
    "max_sleep": 6,
    "timeout": false,
    "root_urls": [
        "https://www.reddit.com",
        "https://www.yahoo.com",
        "http://www.cnn.com",
        "http://www.ebay.com",
        "https://wikipedia.org",
        "https://youtube.com",
        "https://github.com",
        "https://medium.com",
    ],```

**Comment by acyanic** [comment]
My guess is to remove the comma at the end of the final url before the ]

**Comment by prykon** [comment]
Works like a charm now. Thanks!
