### ISSUE TITLE
IPv6 URLs make the script stop

### ISSUE THREAD

**Issue by Random1984** [1tayH/noisy#7]
I left noisy running all night long and this morning I got this log:

```
INFO:root:Visiting https://medium.com/p/a1e0216c8a23
Traceback (most recent call last):
  File "noisy.py", line 265, in <module>
    main()
  File "noisy.py", line 261, in main
    crawler.crawl()
  File "noisy.py", line 232, in crawl
    self._browse_from_links()
  File "noisy.py", line 173, in _browse_from_links
    self._browse_from_links(depth + 1)
  File "noisy.py", line 173, in _browse_from_links
    self._browse_from_links(depth + 1)
  File "noisy.py", line 173, in _browse_from_links
    self._browse_from_links(depth + 1)
  File "noisy.py", line 173, in _browse_from_links
    self._browse_from_links(depth + 1)
  File "noisy.py", line 173, in _browse_from_links
    self._browse_from_links(depth + 1)
  File "noisy.py", line 173, in _browse_from_links
    self._browse_from_links(depth + 1)
  File "noisy.py", line 155, in _browse_from_links
    sub_links = self._extract_urls(sub_page, random_link)
  File "noisy.py", line 120, in _extract_urls
    normalize_urls = [self._normalize_link(url, root_url) for url in urls]
  File "noisy.py", line 62, in _normalize_link
    parsed_url = urlparse(link)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 191, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

```
Only a hanlder is needed for discard the IPv6 URL and it should stay working without problems.

**Comment by 1tayH** [comment]
Hi, thanks for the issue, that's a really nice catch, I didn't expect a parsing library will also have some validation checks. Should be fixed now.
